// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcpwpybakzqgsaacwumm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcHdweWJha3pxZ3NhYWN3dW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTc3OTIsImV4cCI6MjA5MjMzMzc5Mn0.10O839uwd1Y52eBkam3XjNwCQjKlBpJqwdJL4xE12jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});