
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from '@/components/ui/use-toast';

const SUPABASE_URL = "https://ihuksvkozqrrrmqbixfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodWtzdmtvenFycnJtcWJpeGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTc4NzEsImV4cCI6MjA2Mjg3Mzg3MX0.F8WGh2zn_UrRuWehiAYU7B8Ra2ig6by9bTq8HEyVB2k";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-application-name': 'lovable'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Helper function to handle API errors consistently
export const handleSupabaseError = (error: any): void => {
  console.error('Supabase error:', error);
  
  // Format user-friendly error message
  const errorMessage = error?.message || error?.error_description || 'An unknown error occurred';
  
  // Show toast notification with error
  toast({
    title: 'Error',
    description: errorMessage,
    variant: 'destructive',
  });
};

// Export a type-safe function to create secure RLS policies
export function createRLSPolicy<T extends keyof Database['public']['Tables']>(
  tableName: T,
  policyName: string,
  policyDefinition: string
): string {
  return `CREATE POLICY "${policyName}" ON public.${tableName} ${policyDefinition};`;
}

export default supabase;
